[dqn]
actor_model = "agent_dqn.agent.Agent"
learner_model = "agent_dqn.agent.Agent"
aisrv_model = "agent_dqn.agent.Agent"
trainer = "kaiwudrl.server.learner.standard_trainer.StandardTrainer"
predictor = "kaiwudrl.server.actor.standard_predictor.StandardPredictor"
train_workflow = "agent_dqn.workflow.train_workflow.workflow"
eval_workflow = "kaiwu_agent.back_to_the_realm.dqn.eval_workflow.workflow"
exam_workflow = "kaiwu_agent.back_to_the_realm.dqn.exam_workflow.workflow"

[target_dqn]
actor_model = "agent_target_dqn.agent.Agent"
learner_model = "agent_target_dqn.agent.Agent"
aisrv_model = "agent_target_dqn.agent.Agent"
trainer = "kaiwudrl.server.learner.standard_trainer.StandardTrainer"
predictor = "kaiwudrl.server.actor.standard_predictor.StandardPredictor"
train_workflow = "agent_target_dqn.workflow.train_workflow.workflow"
eval_workflow = "kaiwu_agent.back_to_the_realm.target_dqn.eval_workflow.workflow"
exam_workflow = "kaiwu_agent.back_to_the_realm.target_dqn.exam_workflow.workflow"

[diy]
actor_model = "agent_diy.agent.Agent"
learner_model = "agent_diy.agent.Agent"
aisrv_model = "agent_diy.agent.Agent"
trainer = "kaiwudrl.server.learner.standard_trainer.StandardTrainer"
predictor = "kaiwudrl.server.actor.standard_predictor.StandardPredictor"
train_workflow = "agent_diy.workflow.train_workflow.workflow"
eval_workflow = "kaiwu_agent.back_to_the_realm.diy.eval_workflow.workflow"
exam_workflow = "kaiwu_agent.back_to_the_realm.diy.exam_workflow.workflow"